In [2]:
import pandas as pd

In [3]:
bike = pd.read_csv("bike.csv", sep=",")
bike

,datetime,season,holiday,workingday,weather,temp,atemp,humidity,windspeed,casual,registered,count
0,2011-01-01 00:00:00,1,0,0,1.0,9.84,14.395,81.0,0.0000,3,13,16
1,2011-01-01 01:00:00,1,0,0,1.0,9.02,13.635,80.0,0.0000,8,32,40
2,2011-01-01 02:00:00,1,0,0,1.0,9.02,13.635,80.0,0.0000,5,27,32
3,2011-01-01 03:00:00,1,0,0,1.0,9.84,14.395,75.0,0.0000,3,10,13
4,2011-01-01 04:00:00,1,0,0,1.0,9.84,14.395,75.0,0.0000,0,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...
7800,2012-06-05 19:00:00,2,0,1,1.0,23.78,27.275,46.0,16.9979,68,445,513
7801,2012-06-05 20:00:00,2,0,1,1.0,22.96,26.515,49.0,15.0013,44,371,415
7802,2012-06-05 21:00:00,2,0,1,1.0,22.14,25.760,56.0,11.0014,30,253,283
7803,2012-06-05 22:00:00,2,0,1,1.0,22.96,26.515,52.0,7.0015,22,171,193
7804,2012-06-05 23:00:00,2,0,1,1.0,22.14,25.760,56.0,6.0032,20,93,113

In [4]:
bike.shape

(7805, 12)

In [5]:
bike.head(6)

,datetime,season,holiday,workingday,weather,temp,atemp,humidity,windspeed,casual,registered,count
0,2011-01-01 00:00:00,1,0,0,1.0,9.84,14.395,81.0,0.0000,3,13,16
1,2011-01-01 01:00:00,1,0,0,1.0,9.02,13.635,80.0,0.0000,8,32,40
2,2011-01-01 02:00:00,1,0,0,1.0,9.02,13.635,80.0,0.0000,5,27,32
3,2011-01-01 03:00:00,1,0,0,1.0,9.84,14.395,75.0,0.0000,3,10,13
4,2011-01-01 04:00:00,1,0,0,1.0,9.84,14.395,75.0,0.0000,0,1,1
5,2011-01-01 05:00:00,1,0,0,2.0,9.84,12.880,75.0,6.0032,0,1,1

In [6]:
bike.tail(7)

,datetime,season,holiday,workingday,weather,temp,atemp,humidity,windspeed,casual,registered,count
7798,2012-06-05 17:00:00,2,0,1,1.0,24.60,31.060,43.0,0.0000,86,764,850
7799,2012-06-05 18:00:00,2,0,1,1.0,24.60,31.060,43.0,12.9980,111,679,790
7800,2012-06-05 19:00:00,2,0,1,1.0,23.78,27.275,46.0,16.9979,68,445,513
7801,2012-06-05 20:00:00,2,0,1,1.0,22.96,26.515,49.0,15.0013,44,371,415
7802,2012-06-05 21:00:00,2,0,1,1.0,22.14,25.760,56.0,11.0014,30,253,283
7803,2012-06-05 22:00:00,2,0,1,1.0,22.96,26.515,52.0,7.0015,22,171,193
7804,2012-06-05 23:00:00,2,0,1,1.0,22.14,25.760,56.0,6.0032,20,93,113

In [7]:
bike.columns

Index(['datetime', 'season', 'holiday', 'workingday', 'weather', 'temp',
       'atemp', 'humidity', 'windspeed', 'casual', 'registered', 'count'],
      dtype='str')

In [8]:
bike.head(3).T

                              0                    1                    2
datetime    2011-01-01 00:00:00  2011-01-01 01:00:00  2011-01-01 02:00:00
season                        1                    1                    1
holiday                       0                    0                    0
workingday                    0                    0                    0
weather                     1.0                  1.0                  1.0
temp                       9.84                 9.02                 9.02
atemp                    14.395               13.635               13.635
humidity                   81.0                 80.0                 80.0
windspeed                   0.0                  0.0                  0.0
casual                        3                    8                    5
registered                   13                   32                   27
count                        16                   40                   32

In [9]:
bike.info()

<class 'pandas.DataFrame'>
RangeIndex: 7805 entries, 0 to 7804
Data columns (total 12 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   datetime    7805 non-null   str
 1   season      7805 non-null   int64
 2   holiday     7805 non-null   int64
 3   workingday  7805 non-null   int64
 4   weather     7803 non-null   float64
 5   temp        7803 non-null   float64
 6   atemp       7802 non-null   float64
 7   humidity    7804 non-null   float64
 8   windspeed   7804 non-null   float64
 9   casual      7805 non-null   int64
 10  registered  7805 non-null   int64
 11  count       7805 non-null   int64
dtypes: float64(5), int64(6), str(1)
memory usage: 731.8 KB

In [10]:
bike.describe()

,season,holiday,workingday,weather,temp,atemp,humidity,windspeed,casual,registered,count
count,7805.000000,7805.000000,7805.000000,7803.000000,7803.000000,7802.000000,7804.000000,7804.000000,7805.000000,7805.000000,7805.000000
mean,2.182319,0.027546,0.681871,1.419710,19.005967,22.377205,61.239493,13.276312,31.336195,131.398206,162.734401
std,1.088684,0.163680,0.465780,0.642872,7.601849,8.330857,19.888351,8.449740,46.273109,127.076847,155.419640
min,1.000000,0.000000,0.000000,1.000000,0.820000,0.760000,0.000000,0.000000,0.000000,0.000000,1.000000
25%,1.000000,0.000000,0.000000,1.000000,13.120000,15.150000,46.000000,7.001500,3.000000,30.000000,35.000000
50%,2.000000,0.000000,1.000000,1.000000,18.860000,22.725000,61.000000,12.998000,13.000000,100.000000,121.000000
75%,3.000000,0.000000,1.000000,2.000000,25.420000,29.545000,77.000000,19.001200,40.000000,189.000000,238.000000
max,4.000000,1.000000,1.000000,4.000000,38.540000,43.940000,100.000000,56.996900,367.000000,770.000000,873.000000

In [11]:
bike.describe(percentiles=[0.2, 0.5])

,season,holiday,workingday,weather,temp,atemp,humidity,windspeed,casual,registered,count
count,7805.000000,7805.000000,7805.000000,7803.000000,7803.000000,7802.000000,7804.000000,7804.000000,7805.000000,7805.000000,7805.000000
mean,2.182319,0.027546,0.681871,1.419710,19.005967,22.377205,61.239493,13.276312,31.336195,131.398206,162.734401
std,1.088684,0.163680,0.465780,0.642872,7.601849,8.330857,19.888351,8.449740,46.273109,127.076847,155.419640
min,1.000000,0.000000,0.000000,1.000000,0.820000,0.760000,0.000000,0.000000,0.000000,0.000000,1.000000
20%,1.000000,0.000000,0.000000,1.000000,11.480000,14.395000,43.000000,7.001500,2.000000,20.000000,24.000000
50%,2.000000,0.000000,1.000000,1.000000,18.860000,22.725000,61.000000,12.998000,13.000000,100.000000,121.000000
max,4.000000,1.000000,1.000000,4.000000,38.540000,43.940000,100.000000,56.996900,367.000000,770.000000,873.000000

In [12]:
bike.windspeed[5:21]

5      6.0032
6      0.0000
7      0.0000
8      0.0000
9      0.0000
10    16.9979
11    19.0012
12    19.0012
13    19.9995
14    19.0012
15    19.9995
16    19.9995
17    19.0012
18    16.9979
19    16.9979
20    16.9979
Name: windspeed, dtype: float64

In [13]:
bike.temp[bike.temp > bike.temp.mean()]

736     21.32
737     22.96
738     23.78
739     24.60
740     22.96
        ...
7800    23.78
7801    22.96
7802    22.14
7803    22.96
7804    22.14
Name: temp, Length: 3711, dtype: float64

In [14]:
bike["good_temp"] = bike.temp > bike.temp.mean()
bike

,datetime,season,holiday,workingday,weather,temp,atemp,humidity,windspeed,casual,registered,count,good_temp
0,2011-01-01 00:00:00,1,0,0,1.0,9.84,14.395,81.0,0.0000,3,13,16,False
1,2011-01-01 01:00:00,1,0,0,1.0,9.02,13.635,80.0,0.0000,8,32,40,False
2,2011-01-01 02:00:00,1,0,0,1.0,9.02,13.635,80.0,0.0000,5,27,32,False
3,2011-01-01 03:00:00,1,0,0,1.0,9.84,14.395,75.0,0.0000,3,10,13,False
4,2011-01-01 04:00:00,1,0,0,1.0,9.84,14.395,75.0,0.0000,0,1,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
7800,2012-06-05 19:00:00,2,0,1,1.0,23.78,27.275,46.0,16.9979,68,445,513,True
7801,2012-06-05 20:00:00,2,0,1,1.0,22.96,26.515,49.0,15.0013,44,371,415,True
7802,2012-06-05 21:00:00,2,0,1,1.0,22.14,25.760,56.0,11.0014,30,253,283,True
7803,2012-06-05 22:00:00,2,0,1,1.0,22.96,26.515,52.0,7.0015,22,171,193,True
7804,2012-06-05 23:00:00,2,0,1,1.0,22.14,25.760,56.0,6.0032,20,93,113,True

In [15]:
bike[bike.isna().any(axis=1)]

,datetime,season,holiday,workingday,weather,temp,atemp,humidity,windspeed,casual,registered,count,good_temp
273,2011-01-12 20:00:00,1,0,1,NaN,6.56,6.820,50.0,22.0028,2,54,56,False
281,2011-01-13 04:00:00,1,0,1,1.0,5.74,6.060,50.0,NaN,0,4,4,False
343,2011-01-15 19:00:00,1,0,0,2.0,13.12,NaN,39.0,16.9979,14,60,74,False
727,2011-02-14 02:00:00,1,0,1,1.0,14.76,16.665,NaN,19.9995,0,2,2,False
977,2011-03-05 14:00:00,1,0,0,NaN,19.68,23.485,59.0,19.0012,80,118,198,True
1049,2011-03-08 16:00:00,1,0,1,1.0,15.58,NaN,27.0,11.0014,26,82,108,False
1114,2011-03-11 12:00:00,1,0,1,2.0,NaN,15.910,53.0,16.9979,15,96,111,False
1115,2011-03-11 13:00:00,1,0,1,1.0,NaN,16.665,53.0,16.9979,15,92,107,False
1179,2011-03-14 07:00:00,1,0,1,2.0,11.48,NaN,61.0,0.0000,4,84,88,False

In [16]:
bike[(bike.temp>20) & (bike.windspeed>20)].head(5)

,datetime,season,holiday,workingday,weather,temp,atemp,humidity,windspeed,casual,registered,count,good_temp
737,2011-02-14 12:00:00,1,0,1,1.0,22.96,26.515,22.0,30.0026,27,99,126,True
738,2011-02-14 13:00:00,1,0,1,1.0,23.78,27.275,19.0,26.0027,27,93,120,True
739,2011-02-14 14:00:00,1,0,1,1.0,24.60,29.545,15.0,32.9975,14,76,90,True
740,2011-02-14 15:00:00,1,0,1,1.0,22.96,26.515,21.0,43.9989,19,71,90,True
741,2011-02-14 16:00:00,1,0,1,1.0,21.32,25.000,27.0,31.0009,16,102,118,True

In [38]:
bike.loc[739]

datetime      2011-02-14 14:00:00
season                          1
holiday                         0
workingday                      1
weather                       1.0
temp                         24.6
atemp                      29.545
humidity                     15.0
windspeed                 32.9975
casual                         14
registered                     76
count                          90
good_temp                    True
Name: 739, dtype: object

In [39]:
bike.sort_values("count",ascending=False)

,datetime,season,holiday,workingday,weather,temp,atemp,humidity,windspeed,casual,registered,count,good_temp
7606,2012-05-16 17:00:00,2,0,1,1.0,29.52,33.335,51.0,12.9980,104,769,873,True
7631,2012-05-17 18:00:00,2,0,1,1.0,27.06,31.060,27.0,11.0014,134,734,868,True
7630,2012-05-17 17:00:00,2,0,1,1.0,27.06,31.060,31.0,8.9981,133,719,852,True
7798,2012-06-05 17:00:00,2,0,1,1.0,24.60,31.060,43.0,0.0000,86,764,850,True
7607,2012-05-16 18:00:00,2,0,1,1.0,29.52,33.335,51.0,15.0013,97,749,846,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...
4,2011-01-01 04:00:00,1,0,0,1.0,9.84,14.395,75.0,0.0000,0,1,1,False
6035,2012-02-08 03:00:00,1,0,1,1.0,10.66,15.150,65.0,0.0000,0,1,1,False
6036,2012-02-08 04:00:00,1,0,1,1.0,9.84,12.880,70.0,6.0032,0,1,1,False
6034,2012-02-08 02:00:00,1,0,1,1.0,10.66,15.150,65.0,0.0000,0,1,1,False
30,2011-01-02 07:00:00,1,0,0,2.0,16.40,20.455,76.0,12.9980,0,1,1,False

In [40]:
season_desc = pd.DataFrame({
    'season': [1, 2, 3, 4],
    'season_name': ['spring', 'summer', 'fall', 'winter']
})

In [42]:
bike = bike.merge(season_desc, on='season', how='left')
bike

,datetime,season,holiday,workingday,weather,temp,atemp,humidity,windspeed,casual,registered,count,good_temp,season_name
0,2011-01-01 00:00:00,1,0,0,1.0,9.84,14.395,81.0,0.0000,3,13,16,False,spring
1,2011-01-01 01:00:00,1,0,0,1.0,9.02,13.635,80.0,0.0000,8,32,40,False,spring
2,2011-01-01 02:00:00,1,0,0,1.0,9.02,13.635,80.0,0.0000,5,27,32,False,spring
3,2011-01-01 03:00:00,1,0,0,1.0,9.84,14.395,75.0,0.0000,3,10,13,False,spring
4,2011-01-01 04:00:00,1,0,0,1.0,9.84,14.395,75.0,0.0000,0,1,1,False,spring
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7800,2012-06-05 19:00:00,2,0,1,1.0,23.78,27.275,46.0,16.9979,68,445,513,True,summer
7801,2012-06-05 20:00:00,2,0,1,1.0,22.96,26.515,49.0,15.0013,44,371,415,True,summer
7802,2012-06-05 21:00:00,2,0,1,1.0,22.14,25.760,56.0,11.0014,30,253,283,True,summer
7803,2012-06-05 22:00:00,2,0,1,1.0,22.96,26.515,52.0,7.0015,22,171,193,True,summer
7804,2012-06-05 23:00:00,2,0,1,1.0,22.14,25.760,56.0,6.0032,20,93,113,True,summer

In [49]:
bike[["season","count"]].groupby("season").count()

        count
season
fall     1365
spring   2676
summer   2397
winter   1367

In [55]:
p_t = bike.pivot_table("temp","humidity","windspeed")
p_t

windspeed,0.0000,6.0032,7.0015,8.9981,11.0014,12.9980,15.0013,16.9979,19.0012,19.9995,...,36.9974,39.0007,40.9973,43.0006,43.9989,46.0022,47.9988,50.0021,51.9987,56.9969
humidity,,,,,,,,,,,,,,,,,,,,,
0.0,NaN,13.940000,NaN,13.940000,16.400000,14.760000,16.536667,15.0880,15.580,18.040000,...,NaN,18.04,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,21.320,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,22.1400,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
93.0,11.097333,12.124286,9.871538,10.832632,10.933333,11.616667,11.778182,11.8900,11.480,13.530000,...,NaN,NaN,9.84,NaN,NaN,NaN,NaN,NaN,NaN,NaN
94.0,20.208444,21.531613,21.511333,21.574483,22.842857,20.629474,20.741176,21.4840,21.156,21.115000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
96.0,NaN,NaN,NaN,11.480000,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
97.0,NaN,NaN,24.600000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
100.0,16.963750,17.981429,19.844000,18.118095,16.318000,19.024000,17.512857,19.5775,15.580,15.648333,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [57]:
group = bike[["season","count"]].groupby("season").sum()
percentages = (group / group.sum()) * 100
percentages

            count
season
fall    20.096021
spring  24.571111
summer  38.673786
winter  16.659082